// Notion Crafts — deterministic icon build pipeline.
//
//   node scripts/build-icons.mjs --report   # coverage report only
//   node scripts/build-icons.mjs            # write generated icon data
//
// Sources Phosphor (MIT, primary — regular/fill/duotone weights) with a Tabler
// (MIT) fallback. Each manifest key resolves to per-weight inner SVG markup;
// the renderer scales via viewBox, so no path math here. Gradient is derived
// at render time from the fill markup.

import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { flatManifest } from './manifest.mjs';

const require = createRequire(import.meta.url);
const ph = require('@iconify-json/ph/icons.json');
const tb = require('@iconify-json/tabler/icons.json');
const __dirname = dirname(fileURLToPath(import.meta.url));

const REPORT = process.argv.includes('--report');

// Aliases: our key -> real Phosphor base name (for keys whose label differs
// from the library's icon name). Each maps to a visually distinct glyph.
const ALIAS = {
  'check-double': 'checks',
  'goal': 'flag-checkered',
  'sticky-note': 'notepad',
  'streak': 'fire-simple',
  'document': 'article',
  'comment': 'chat-circle-dots',
  'meditation': 'person-simple-tai-chi',
  'bracket': 'code-simple',
};

// Keys with no good distinct glyph in Phosphor/Tabler — dropped so we never
// ship a broken or duplicate tile. (Still leaves us well above 550.)
const DROP = new Set(['todo', 'pages', 'hot-dog', 'french-fries', 'taco', 'sushi', 'sd-card', 'ring']);

const phHas = (n) => Object.prototype.hasOwnProperty.call(ph.icons, n);
const tbHas = (n) => Object.prototype.hasOwnProperty.call(tb.icons, n);

// Resolve one manifest entry to { key,label,cat, src, vb, o,f,d }.
// `forceSrc` (m.src) pins the source so an expansion icon intended as Tabler
// isn't silently captured by a same-named Phosphor glyph.
function resolve({ key, label, cat, src: forceSrc }) {
  const base = ALIAS[key] || key;

  // Phosphor primary (skipped when an entry is pinned to Tabler).
  if (forceSrc !== 'tb' && phHas(base)) {
    return {
      key, label, cat, src: 'ph', vb: ph.width || 256,
      o: ph.icons[base].body,
      f: (phHas(base + '-fill') ? ph.icons[base + '-fill'] : ph.icons[base]).body,
      d: (phHas(base + '-duotone') ? ph.icons[base + '-duotone'] : ph.icons[base]).body,
    };
  }

  // Tabler (stroke). outline = native; filled = -filled when it exists, else
  // the stroke; duotone is synthesized (soft fill underlay + the outline).
  if (tbHas(base)) {
    const outline = tb.icons[base].body;
    const filled = tbHas(base + '-filled') ? tb.icons[base + '-filled'].body : outline;
    const duo = `<g opacity="0.2">${filled}</g>${outline}`;
    return { key, label, cat, src: 'tb', vb: tb.width || 24, o: outline, f: filled, d: duo };
  }

  return null;
}

// Primary manifest + curated expansions (manifest-2/3/4.json, key = library name).
const manifest = flatManifest().filter(m => !DROP.has(m.key));
const fs = require('node:fs');
let expand = [];
for (const n of [2, 3, 4]) {
  try { expand = expand.concat(JSON.parse(fs.readFileSync(join(__dirname, `manifest-${n}.json`), 'utf8'))); } catch {}
}

const seenKeys = new Set();
const resolved = [];
const missing = [];
for (const m of [...manifest, ...expand]) {
  if (seenKeys.has(m.key)) continue;
  seenKeys.add(m.key);
  const r = resolve(m);
  if (r) resolved.push(r);
  else missing.push(m);
}

const byCat = {};
for (const r of resolved) byCat[r.cat] = (byCat[r.cat] || 0) + 1;

console.log('=== Icon build coverage ===');
console.log('manifest (deduped):', manifest.length);
console.log('resolved          :', resolved.length,
  `(ph ${resolved.filter(r => r.src === 'ph').length}, tb ${resolved.filter(r => r.src === 'tb').length})`);
console.log('MISSING           :', missing.length);
if (missing.length) {
  console.log('\nUnmatched keys:');
  for (const m of missing) console.log('  -', m.key, `(${m.cat})`);
}

if (REPORT) {
  console.log('\nPer-category:');
  for (const { cat } of (await import('./manifest.mjs')).CATEGORIES) {
    console.log('  ', String(byCat[cat] || 0).padStart(3), cat);
  }
  process.exit(0);
}

// Emit generated data module consumed by the React app.
const out = resolved.map(r => ({
  k: r.key, l: r.label, c: r.cat, vb: r.vb, o: r.o, f: r.f, d: r.d,
}));
const file = join(__dirname, '..', 'src', 'data', 'icons.generated.js');
const header = `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Sources: Phosphor Icons (MIT) + Tabler Icons (MIT). ${out.length} icons.
`;
writeFileSync(file, header + 'export const ICONS = ' + JSON.stringify(out) + ';\n');
console.log('\nWrote', out.length, 'icons ->', file);
